name: MC_Tutorial
version: '${project.version}'
main: cat_std.broseidon.mc_tutorial.MC_Tutorial
api-version: '1.20'
authors: [Broseidon.Java]
description: Tutorial to create Minecraft Plugin
website: https://leminhbao.com
